[package]
name = "dividends"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.40"
csv = "1.3.0"
env_logger = "0.11.2"
log = "0.4.20"
serde = { version = "1.0.197", features = ["serde_derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.114"
